name = "cf-url-shortener"
workers_dev = true
compatibility_date = "2022-01-20"
main = "build/worker/shim.mjs"
kv_namespaces = [
    <config dict>
]# main = "src/index.js"

[vars]
WORKERS_RS_VERSION = "0.0.18"

[build]
command = "cargo install -q worker-build && worker-build --release" # required

[[rules]]
globs = ["**/*.wasm"]
type = "CompiledWasm"

[[d1_databases]]
binding = <DB binding>                                       # i.e. available in your Worker on env.DB
database_name = <DB name>
database_id = <DB ID>

# read more about configuring your Worker via wrangler.toml at:
# https://developers.cloudflare.com/workers/cli-wrangler/configuration
